apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.fullname" . }}-db
  labels:
    app.kubernetes.io/name: database-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  DB_HOST: {{ .Values.database.host | b64enc | quote }}
  DB_PORT: {{ .Values.database.port | toString | b64enc | quote }}
  DB_NAME: {{ .Values.database.name | b64enc | quote }}
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
